### ISSUE TITLE
create-chat

### ISSUE THREAD

**Issue by Grsaiago** [Grsaiago/ft_transcendence#12]
Essa branch tem como objetivo a criação do chat :D

**Comment by Grsaiago** [comment]
Because users can add and remore other users from their groups at runtime, by befriending or unfriending/blocking another user, we gotta find a way to map a user to their respective channel (if connected). Apparently there isn't a native way to do it, so we'll have to:
- Look into redis_client. 
- Move the 'dynamic_groups' logic into a set on redis. The key will be the user id and the values will be the specified groups that the user is assotiated with. General Registry and Cleanup will be done at ChatSocket.connect and ChatSocket.disconnect methods respectively (oof). Because the websocket connection is only established with authorized users, we have access to the user object via the self.scope['user'] from within the socket, so it should not be an issue to add the user id as a key, since it's the mos basic common denominator between both the ChatConsumer and the User objects.
- The add_to_group and remove_from_group methods of the ChatSocket will have to be moved into the user Model (?)
- probably add the key as f"user_groups:{user.id}" (validate naming convention with the team)

ou a gente esquece essa merda toda de async e coloca pra dar connect no websocket só quando o usuário tá na página /chat e desconectar quando sair dela. daí se alguma coisa mudar é só dar refresh na página ou sair e voltar que recarrega as parada. (sou bem a favor dessa aqui em)

**Comment by Grsaiago** [comment]
#### Para o problema de mapear um usuário a um channel:
- Invés de substituir a variável 'dynamic_groups' por um set no redis, a gente pode guardar o channel.self.channel_name em uma chave no redis que vai ser f"user_channels:{user.id}", que vai ser alimentada no channel.connect e deletada no channel.disconect.

#### Para o problema de atualizar a 'dynamic_groups' a partir de um usuário:
- Tendo o mapeamento Usuário->channel_name feito, a gente pode cirar um método no channel do tipo 'command_remove_from_group' que vai fazer a mesma coisa que o remove from group. Só que, invés de receber um group_id, ele vai receber um event que, nesse dicionário event, vai ter uma chave 'group_id'. Esse método vai ser um handle pra group_send. Assim, o usuário consegue pegar o id do channel pelo redis, dar um group_send passando a chave que ele quer remover e o objeto que tem o a variável 'dynamic_groups' vai rodar esse receber esse evento emitido, rodar o método, extrair o group_id do dicionário de evento e fazer enfim a remoção.

p.s: Obrigado, @izacabral  tu é braba

**Comment by Grsaiago** [comment]
Eu ,@mari-aragao e @FernandaMatt estamos integrando o chat e a parte do front na branch 'chat-integration'.
Estamos ajeitando algumas implementações dos dois lados pra que tudo funcione.

**Comment by FernandaMatt** [comment]
A integração do chat e manutenção de um histórico rústico foi criada.

Melhorias:

1. Chat funcional independente da aba que o usuário está, enquanto estiver logado.
2.1 inicializar o map ao logar com todos os chat_ids de amigos, ao receber mensagem, atualizar histórico sempre
